<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-JPIFOPI" failures="1" tests="3" name="Parllel Test" time="35.111" errors="0" timestamp="2022-11-03T04:21:52 PDT">
  <testcase classname="testNGPractice.VarifyLoginFunctionality" name="VarifyLogin" time="0.013"/>
  <testcase classname="testNGPractice.VarifyLogoutFunctionality" name="varifyLogOut" time="3.707"/>
  <testcase classname="testNGPractice.VarifyAddtocartAllProducts" name="addToCartallProducts" time="6.771">
    <failure type="java.lang.AssertionError" message="expected [5] but found [6]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [6]
at testNGPractice.VarifyAddtocartAllProducts.addToCartallProducts(VarifyAddtocartAllProducts.java:30)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- addToCartallProducts -->
</testsuite> <!-- Parllel Test -->
